### ISSUE TITLE
add option to pass EID to Qualtrics for embedding or exposing in survey data

### ISSUE THREAD

**Issue by tomato-gits** [longhornopen/qualtrics-lti#1]
Probably want to include option to disable on survey-by-survey basis to allow for anonymous surveys, with note on launch page confirming that survey is anonymous.

**Comment by chrispittman** [comment]
'EID' is a UT-Austin-specific term for logins; we'll pass it as 'userid' or something similar.

**Comment by chrispittman** [comment]
`sis_user_id` is now getting passed to the Qualtrics survey, if the LMS provides it.
