### ISSUE TITLE
(Feature) Provide some backend logging for administrative auditing and debugging

### ISSUE THREAD

**Issue by jonespm** [longhornopen/qualtrics-lti#10]
We recently had an issue come up where some students were unable to get into the Qualtrics survey. Because of lack of logging information from this app and lack of details in the error report we can't determine if the problem was from this tool or from Canvas. I'm filing this as an issue as I'm not sure the best way to implement this. I think using Laravels console logging would be fine and it doesn't need to be in the database. 

The only logging that comes through when running are access request from the web server. It would be useful to have a little more logs.

_Probably_ most of these would go in the AppController. I think miminally it would be nice to have a log message when

* a student launches a survey (`getTestBegin`?)
* a student completes a survey and and a "grade" is passed back (`getTestEnd`?)

Also whenever there's an error returned to the user it would probably be useful to have an error log message, for instance the tool displays errors like 
https://github.com/longhornopen/qualtrics-lti/blob/eaf859a267b09f0b135268163e81d0b7c7abc57a/web/app/Http/Controllers/AppController.php#L85
and
https://github.com/longhornopen/qualtrics-lti/blob/eaf859a267b09f0b135268163e81d0b7c7abc57a/web/app/Http/Controllers/AppController.php#L130

But we don't have any information about that. And not all students contact us. 

If it included any information about the user, course and survey id it would be probably be best..

**Comment by chrispittman** [comment]
Some of this info you have already, albeit not in log form.  If a student starts a survey, there'll be an entry in the `assignment_responses` table.  If a student completes a survey, that entry will have non-null 'score' entry, which was sent to it by Qualtrics.  This info is also shown in the tool itself, in a table at the bottom of the page.

The two error messages you reference only show up if we're unable to contact the LMS to upload a score, which should hopefully be a rare occurrence, and which the teachers can re-initiate an attempt on their own.

My personal take is that this app is simple enough that if you need to go digging into log files to debug it, that's a sign that we've failed to provide a good tool.  Can you describe the specific issue(s) you were having, that made you want this feature?  Because we're more interested in fixing those more fundamental problems.

**Comment by jonespm** [comment]
We're not really sure, we're **not** getting a lot of feedback from a user who had a lot of problems with this and there's no logging so nothing else we really can tell them other than there was a lot of activity.

There were over 500 students and it looks like it might have been misconfigured to Privacy: "Private/Anonymous" so I don't know how to map the user_names back easily. (Or really at all since they're LTI ids).  

There are 397 entries for that course in the assignment_responses. There were 39 where the score is null. So I'm not sure where the problem occurred. That 10% seems like a large number. 

Perhaps there's nothing more that would be seen with the logs here and maybe if we had actual user ID's/emails that would be sufficient. If it never comes back from Qualtrics I guess we wouldn't know. I'll look into this config.

**Comment by chrispittman** [comment]
Yeah, in LTI Private mode we're not going to have a lot of info to log for you, other than opaque IDs, which don't really help a lot.

Null scores mean the students didn't make it back to us.  This is usually not a technical problem...it's been our experience that some percentage of students just don't finish the surveys (i.e., get to the point where they hit the return URL and get sent back to us).  It's usually not as high as 10%, but if the survey at any point shows a message like _"Congrats, you're done!  Click here to..."_, students will only read the first sentence, take it at face value, and close the window at that point.  We also occasionally have surveys that are just plain missing the end-of-survey step, which the 'Test' button is meant to help teachers discover.

We don't close off students on our end when there's an incomplete survey - as long as the assignment is still open in Canvas, they can try again.  Or, if you want to administratively give these students credit, you can:
* Find the 'assignment_responses' rows with a null 'score' and set them to the score you want.
* Go into the tool's UI.  Students you altered in the step above will have a 'resend score' button.  Click it.
In that table, 'created_at' is the date that the student started the tool, and 'updated_at' is the date the row was last altered, which is probably when we got a redirect from Qualtrics.

Given that it doesn't sound like additional logs would have helped you there, I'm going to close this one as "won't fix".  We think every event we would be logging is already adequately represented in the 'assignment_responses' table.  But we're very interested in helping streamline out any issues that would have sent you hunting for log files.  Let us know in a fresh issue if you find any.
