### ISSUE TITLE
Getting a blocked popup on first launch when launching in iframe: LTI 1.3

### ISSUE THREAD

**Issue by jonespm** [longhornopen/qualtrics-lti#13]
When configuring this application as LTI 1.3 and launching for the first time in Chrome the user is getting a message that a popup is blocked. If this isn't clicked and allowed the application doesn't display. 

If popups are allowed and the page refreshed, the survey configuration opens up in a pop-up window. 

However the next time it's refreshed it opens fine in an iframe. This can be reset back to a broken state by blocking popups again and clearing cookies.

The app is working fine when opening in a new window but we'd prefer to run in an iframe, even though this is harder to setup.

Do you run the app like this and have you seen this behavior? Do you know why this initial popup would be happening? Are you using instructure.com or a vanity domain for your Canvas instance? 

It looks like the lavravel-celtic-lti is a few versions behind and it was locked to 4.9.0 specifically, but I don't see any recent fixes there that would help this?

It *thought* it might be related to the cookie check in `parseMessage` but calling `getMessageParameters()` doesn't run this check. 

There's no problem with the LTI 1.1 launch.

Any hints would be appreciated, I'm not seeing any errors or issues in the browser console or log from this app.

**Comment by jonespm** [comment]
It's entirely possible I have something misconfigured too, but I've been going over the installation instructions.

It looks like the popup _seems_ to be coming from Canvas code because for this to the target is _blank. 

I cleared out most of the values below. 

```
<html>
    <head>
        <title>1EdTech LTI message</title>
        <script type="text/javascript">
            //<![CDATA[
            function doOnLoad() {
                if ((document.forms[0].target === '_blank') && (window.top === window.self)) {
                    document.forms[0].target = '';
                }
                document.forms[0].submit();
            }

            window.onload = doOnLoad;
            //]]>
        </script>
    </head>
    <body>
        <form action="/lti" method="post" target="_blank" encType="application/x-www-form-urlencoded">
            <input type="hidden" name="utf8" value="✓"/>
            <input type="hidden" name="authenticity_token" value=""/>
            <input type="hidden" name="id_token" value=""/>
            <input type="hidden" name="state" value=""/>
            <input type="hidden" name="lti_storage_target" value="_parent"/>
            <input type="hidden" name="_new_window" value=""/>
        </form>
    </body>
</html>

```

If I put a breakpoint in there and clear the target I get an error back from the app until the cache is cleared again.
`state parameter is invalid or missing`

**Comment by jonespm** [comment]
Okay never-mind, this code in Celtic https://github.com/celtic-project/LTI-PHP/blob/62ac401509e0122e3af4e768802dc0df15161ef9/src/Util.php#L384

https://github.com/celtic-project/LTI-PHP/blob/62ac401509e0122e3af4e768802dc0df15161ef9/src/System.php#L1234

So is some problem with cookies?

I saw PHPSESSID getting blocked and tried to fix for that but that didn't seem to fix it https://github.com/tl-its-umich-edu/docker-base-images/pull/26

**Comment by chrispittman** [comment]
We're seeing this behavior too.  I'm wondering if this is a recent change in Chrome.  Investigating.

**Comment by chrispittman** [comment]
Here's my understanding of the situation.

In early 2020, as an ad-privacy measure, Chrome made a change to no longer allow iframes to set cookies in certain situations.  They didn't publicize exactly what those situations were, but once you'd interacted with an iframed site a few times, Chrome inferred from your usage that you trusted it, and would start allowing cookies to be set.

Several LTI implementations, including Celtic's, adapted to this strategy by checking to see if the cookies they set were actually being returned by the browser.  If they weren't, that meant that the browser was refusing to set the cookies, and the LTI tool would then open up a popup window and try setting cookies there.  Popups aren't iframes and aren't subject to these cookie restrictions.  So what you'd see is that an LTI tool would open in a popup a few times until the user had built up enough of a history with the LTI tool's server that Chrome decided to trust it, and then the tool would start loading in an iframe successfully instead.  (Sometimes, this only takes a single usage for Chrome to decide to do this.)  

Chrome's popup blocker is blocking that initial attempt to load the tool in a new window.  (I'm not sure if popup blocking got more aggressive recently; I wasn't able to replicate this problem in our browser-testing service where we test against multiple versions of Chrome.)  Eventually, once the user's successfully gotten to the site and used it for a bit, Chrome should start allowing the iframe to work, but the metrics for when that decision happens are entirely on Chrome's side.

So... you can instruct users to allow the popups, and eventually Chrome will learn to trust the server you're running Qualtrics-LTI on and eventually not need those popups in the first place.  Or, you can set the tool to always open in a new window, which is annoying but sidesteps the problem.  I can't think of a third solution offhand, given that so much of this is happening out of our hands in either the browser or the LMS, but I'm open to ideas if you have any.

**Comment by jonespm** [comment]
Hmm, I'm not sure. I know this is something that is intended to be improve in a future LTI release but also other libraries we're doing don't seem to cause this issue. I haven't looked at this enough to see what the difference is. 

For instance [pylti13 package does a cookie check](https://github.com/dmitry-viskov/pylti1.3/blob/master/pylti1p3/cookies_allowed_check.py) too but Chrome doesn't have a problem with that.

I'm going to be off for a week and not sure if anyone here will look at this in the meantime. Thanks for confirming your thoughts and providing feedback. I'll look at this some more in a week or so if nobody does earlier.

**Comment by chrispittman** [comment]
If I'm interpreting that Python correctly, it's offering you a link to click, which counts as a user action, which is enough to cause the popup blocker to not kick in.  The Celtic PHP library is just automatically auto-submitting.  I'll open up an issue with the Celtic authors and see what their suggestion is.

**Comment by jonespm** [comment]
Right it has the window.open in an onclick event and offers the user a link to click on the page rather than just try to automatically open a popup and have the popup blocker kick in and block it.

However the link doesn't appear for *most* users (in Chrome specifically) and it just displays fine in an iframe. Users in Safari tend to get blocked more than other browsers. But at least it's more obvious on how to proceed. Most people don't notice the popup blocked icon at all. I wonder if there is a problem with some session cookie. It looked like everything was configured fine in your app for Laravel but _something_ was setting `PHPSESSID ` sometimes and that was getting blocked because it wasn't SameSite None/Secure.

**Comment by chrispittman** [comment]
https://github.com/celtic-project/LTI-PHP/issues/50

**Comment by chrispittman** [comment]
> I wonder if there is a problem with some session cookie. It looked like everything was configured fine in your app for Laravel but _something_ was setting `PHPSESSID ` sometimes and that was getting blocked because it wasn't SameSite None/Secure.

I'm a little confused here - the app's cookies are SameSite None, Secure, HTTP-Only out of the box (https://github.com/longhornopen/qualtrics-lti/blob/main/web/config/session.php#L171-L199) which is what it's supposed to be to allow iframed cookies at all.  If you're changing that in a fork or via env vars, don't.  The browser still has the ability to reject cookies from sites it's never seen before, which is what's happening here, and why it works once the user's used the site once.  Above is a link to the issue in the Celtic library, where I'm hoping to start a discussion.

**Comment by chrispittman** [comment]
We should now have a workaround for Chrome's popup blocker; we'll offer a message along with a manual Submit button for the user to click.  (Or, they can whitelist your LMS in their popup blocker, which should also work.)  That message will go away after 60 seconds (a nonce set by Canvas during the launch process expires then).

This fix is in the `20230404` Docker image as well.

This appears to fix the problem for our deployments of this tool, so I'm closing this issue.  But I'd appreciate feedback about how it's working for you.  Happy to re-open this if we haven't quite nailed the workaround here.

**Comment by jonespm** [comment]
Hmm, so when I set up an assignment all I do see a button that says:

<img src=https://user-images.githubusercontent.com/27447/230170746-591f6617-8d4f-4fd6-9f44-8d51616c5fd6.png width=400px>

I click the button and nothing seems to happen but it does load a page and just go back to this same page. I haven't had a place to setup a survey yet and am using this as an instructor.

The link goes to (I replaced the user id)

`https://jonespm-qualtrics-lti.loophole.site/app?return_url=https%3A%2F%2Fjonespm-qualtrics-lti.loophole.site%2Fapp%2Fresponse&sis_user_id=0000000`

I switched back to the old tag and it works. I'm not sure what's different.

**Comment by chrispittman** [comment]
This is the screen we show to students; are you sure you're logged in as an instructor when you're seeing this?  We store whether or not you're a teacher in a session variable - do you maybe have two instances of this open in the same browser, one as a student and one as a teacher?

**Comment by jonespm** [comment]
So it looks like I was launching as an admin that didn't have a specific role in the course. 
```
  "https://purl.imsglobal.org/spec/lti/claim/roles": [
    "http://purl.imsglobal.org/vocab/lis/v2/institution/person#Administrator",
    "http://purl.imsglobal.org/vocab/lis/v2/institution/person#Instructor",
    "http://purl.imsglobal.org/vocab/lis/v2/institution/person#Student",
    "http://purl.imsglobal.org/vocab/lis/v2/system/person#User"
  ],
```

The previous version display for an an admin without a course membership was same as instructor. Now they have to be an instructor in the class. Was this an intended change? Perhaps it's a new issue if not.

This _seems_ to be what's required now `"http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor",`.

**Comment by chrispittman** [comment]
This wasn't an intended change - LTI 1.3's role system is a lot richer than LTI 1.2's, and Admins-but-not-Instructors probably got lost in the mix.  (We don't have many of those, which is why we didn't notice this ourselves.)

I've opened up issue #14 to track this - please add comments if you have any more, or set up notifications if you'd like to know when this is fixed.

**Comment by jonespm** [comment]
Thanks for filing that.

Preliminary testing of this iframe issue does look to be working correctly now so that's good news! Going to do a little more testing in some other browsers and with more people once #14 is figured out.
