### ISSUE TITLE
Pass email address as a parameter as sis_user_id isn't always available

### ISSUE THREAD

**Issue by jonespm** [longhornopen/qualtrics-lti#19]
I noticed back in issue #1 you'd added a feature for passing `sis_user_id`. However this value isn't mentioned in the documentation for setting up the survey. Additionally if the ID isn't set for that user nothing is sent.

We had a request for having the ID's available on the survey and think the next best thing to send is the email address. From what I can see is set for everyone. It would also be nice to mention these are available to setup as embedded data in the setup documentation. 

It could be worthwhile to give the user an option if they'd like to pass these values along or not in the setup but I don't know if this is necessary since if you don't include them in your survey they essentially aren't used, just passed along in the URL. 

This is something we could implement if you don't have time in the next week or so. 

Thanks!

**Comment by chrispittman** [comment]
It's not a bad idea!  I'm not likely to have time to work on it next week myself, but I'd be happy to help you get a PR together, if you have a deadline.

**Comment by melindakraft** [comment]
I would classify it as a requirement that the collection of user data is a configurable option so we can still support the anonymous data collection when needed.

**Comment by jonespm** [comment]
@melindakraft This currently already sends over the `sis_user_id ` on every request. It sounds like a different/separate issue if we wanted to make this configurable of whether or not to send it. Even though it's sent every time, if the user doesn't add this field to their Qualtrics survey then it's not captured.

**Comment by jonespm** [comment]
Okay I'm going to split out the documentation to a separate issue and put this one in since it's simpler. We also had another request to encrypt the parameters to prevent URL tampering which I'll create as another issue.
