### ISSUE TITLE
Provide some documentation to instructors about how to use user identifier variables in Qualtrics

### ISSUE THREAD

**Issue by jonespm** [longhornopen/qualtrics-lti#20]
Qualtrics LTI sends sis_user_id in #1  and in #19 user_email.  I noticed that there isn't any mention of these values in the instructor facing documentation and about how you'd set up your survey to capture it. This should be included in the documentation page.

**Comment by chrispittman** [comment]
This documentation is now at /docs/student_data_capture, and there's a link to it near the checkboxes that turn the feature on.
