### ISSUE TITLE
Move styles from views to css (or sass) for easier local branding

### ISSUE THREAD

**Issue by jonespm** [longhornopen/qualtrics-lti#4]
We wanted to change up some of the colors (like #BF5700) but noticed they were all [hardcoded in an inline style in the php file. ](https://github.com/longhornopen/qualtrics-lti/blob/30145bcc9a2bcaa39133e2a87ace6c36ae4bcc09/web/resources/views/welcome.blade.php#L14)

It would be nice if these could be moved so we only had to update a style sheet rather than change code.

**Comment by chrispittman** [comment]
Yeah, agreed.  Those are now in https://github.com/longhornopen/qualtrics-lti/blob/main/web/resources/sass/app.scss instead.

We're also now checking for an APP_HIDE_LONGHORNOPEN_BRANDING environment variable, if you want to turn off the 'provided by Longhorn Open' footer entirely.  (Although we'd love a credit somewhere outside of the app if you do this!)

Take a look at the current main branch and see if it'll work for you.  If so, I can tag a new release.

**Comment by jonespm** [comment]
We're fine leaving the branding or copyright. 

Just sounded like we wanted the colors of the header/footer and buttons to better match the theme used in Canvas. I think it's possible to pass some of that as custom variables with Canvas in the launch but as long as we can easily change it without touching the other code that'd be great.

**Comment by jonespm** [comment]
Yeah I think this change will work, thanks for the quick update!

**Comment by chrispittman** [comment]
Cool.  I tagged a git release and a new Docker image, both with today's date.  Thanks for letting us know!

**Comment by jonespm** [comment]
So we were trying to use this and because the css is compiled we found it easier just to do take the build image and do a search/replace of 

`sed -i s/background-color:\#bf5700/background-color:\#00274c/g /var/www/html/public/css/app.css`

rather than rebuild from source. And that mostly worked except that the Longhorn Open logo on the footer was also the changed color which didn't match well. And there might be instances of bf5700 that we don't want to change.

Have you looked into just for a css override like with https://stackoverflow.com/a/46940248/3708872

I'm thinking we could just put that into the blade and have something there blank by default. Then I can copy in a file that has like.

```
.page_home .header {
    background-color: #00274c;
}

.page_home .footer {  
    background-color: #00274c;
}
.page_home .footer .float-right {
   background-color: #bf5700
}
```

Hmm, I might just also be able to append that to the end of app.css rather than changing anything?

**Comment by chrispittman** [comment]
Hmm.  Yeah, it shouldn't be this hard.

If we included a blank 'custom.css' file, would you be able to inject your own version of that file (with the blockquote above as contents) into the image you're running?  Is that a doable workflow for you?

**Comment by jonespm** [comment]
Yeah, I think that would work great, something that was just after the app.css in the template and I could just do a `COPY `to get it in there. I don't see any easier way of making that change without rebuilding. We really just need to change a few styles.

I could also just append it to app.css if you don't want to make this change but I didn't think of that until I was typing this out. It probably would be cleaner to keep them separate though.

**Comment by chrispittman** [comment]
The new file at `public/custom/custom.css` now gets applied to every page.  If you want to inject your own version of that file, great.  `public/custom` will only ever hold per-install customizations in the future, if you're using Docker and it's easier to mount that directory as a volume, and inject your files that way, that should work too.

The '20230215' Docker image contains this change.

Closing the issue, on the assumption that this gets you going, but let us know how it works out!

**Comment by jonespm** [comment]
Awesome, yeah was thinking I could just mount a volume there too if it was separate. Thanks for the quick fix!
