### ISSUE TITLE
Plans to upgrade to LTI 1.3?

### ISSUE THREAD

**Issue by jonespm** [longhornopen/qualtrics-lti#5]
On the README it says for LTI 1.3 "Coming soon..."

Have you worked on that at all for this project? With LTI 1.1 certification no longer available and more tools moving to 1.3 we're just trying to get an update on if/when tools we're running are moving to 1.3. 

I know [IMS has an sample library](https://github.com/IMSGlobal/lti-1-3-php-library) for that and this [Packback fork](https://github.com/packbackbooks/lti-1-3-php-library) has had a ton of changes since 2020. I haven't used anything in PHP though. 

Thanks!

**Comment by chrispittman** [comment]
We have a new-ish [Laravel LTI library](https://github.com/longhornopen/laravel-celtic-lti) that supports LTI 1.1/1.2 and 1.3 simultaneously.  So we're not planning a hard cutover date where we turn off 1.2 and turn on 1.3 in the same release.  I haven't had a chance to update this app to use the newer versions of that library just yet, but it should be a pretty easy swapover.

If you have a date that you're looking to have LTI 1.3 enabled by, let us know and we can certainly work with you on that.  Left to our own devices, we're going to try to get 1.3 support for this app sometime in 2022.  (Personally, I'd be shocked if existing LMS vendors turned off 1.1/1.2 support without years of advance notice, but we don't want to get caught flat-footed if I'm wrong about that, given the number of homegrown LTI apps we have at UT Austin.)

**Comment by jonespm** [comment]
Hi @chrispittman . Does the commit on 142d4d3656ef948ef80f310ecc0c4de80994c99d fully resolve this issue?

**Comment by chrispittman** [comment]
Likely, but I haven't had a chance to test it myself just yet, so I haven't felt confident tagging it as a release.  Launching the tool seems to work fine, but grade passbacks are still untested at this point.  (Our test instance of canvas responds to grade passbacks with a 403 response, so I need to rig up a limited test in production.)  Hoping to get to that soon after our fall semester gets settled in.

If you do any testing yourself before then, I'd love to hear what your findings are!  I see we're both on the Canvas EDU Slack - feel free to hit me up there if it'd help to chat.

**Comment by chrispittman** [comment]
Release 2022-09-06 adds tested LTI 1.3 support, along with a new page (at `/lti/help`) containing LTI 1.3 installation instructions (focusing on Canvas for now because it's what I know best).

Please let us know any bug reports or comments you have!
