### ISSUE TITLE
add option for csv download of grade passback logs

### ISSUE THREAD

**Issue by meganmmoeller** [longhornopen/qualtrics-lti#8]
add option for csv download of grade passback logs

would like to have the option to download the grade passback logs in the table (including date/time stamp and sis_user_id and other information in Responses table shown in tool interface)

**Comment by jonespm** [comment]
It looks like this project is using bootstrap with jQuery so this could be converted to a [bootstrap table and the export ](https://bootstrap-table.com/docs/extensions/export/) extension used.

This might be a little heavy but would probably provide some other perks, though this looks simpler. https://jsfiddle.net/gengns/j1jm2tjx/
